language: node_js
node_js:
- '4.6'
sudo: false
cache:
  directories:
  - node_modules
addons:
  postgresql: "9.4"
before_script:
 - psql -c 'create database webmaker_testing' -U postgres
after_script:
 - npm run test:reportcoverage
services:
  - redis-server
